// throw
function sayMyName(name = '') {
  if (name === '') {
    throw 'Nome é necessário'
  }

  console.log('depois do erro')
}

// try...catch

try {
  sayMyName()
} catch (e) {
  console.log(e)
}

console.log('após o try/catch')
